version: "3.7"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: one_city_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    image: eqw21/technical1
    depends_on:
     - db
    ports:
     - "80:80"    
    labels:
      kompose.service.type: LoadBalancer